# Generated by Django 4.1.6 on 2023-03-06 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('measurement', '0002_alter_measurement_temperature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['-id']},
        ),
    ]
